import { vi } from "vitest";

/** Minimal `ws_store_new()` return for shell component tests. */
export function ws_store_stub() {
  return {
    latest_status: () => ({
      type: "status" as const,
      state: "idle" as const,
      current_app: "unknown",
      current_app_since: undefined,
      candidate_app: undefined,
      candidate_duration_s: 0,
      transition_threshold_s: 0,
      poll_seconds: 0,
      poll_count: 0,
      last_poll_ts: new Date(0).toISOString(),
      uptime_s: 0,
      activity_provider: {
        provider_id: "activitywatch",
        provider_name: "ActivityWatch",
        state: "checking" as const,
        summary_available: false,
        endpoint: "http://localhost:5600",
        source_id: undefined,
        last_sample_count: 0,
        last_sample_breakdown: {},
        setup_title: "Activity source unavailable",
        setup_message:
          "Manual labeling still works, but activity summaries and automatic activity tracking are unavailable until this source is set up.",
        setup_steps: [
          "Install and start ActivityWatch.",
          "Confirm the local server is reachable at http://localhost:5600.",
          "If you use a custom host, update aw_host in config.toml and restart taskclf.",
        ],
        help_url: "https://activitywatch.net/",
      },
      aw_connected: false,
      aw_bucket_id: undefined,
      aw_host: "http://localhost:5600",
      last_event_count: 0,
      last_app_counts: {},
    }),
    latest_prediction: () => undefined,
    badge_display_override: () => ({
      enabled: false,
      label: undefined,
    }),
    latest_tray_state: () => ({
      type: "tray_state" as const,
      model_loaded: false,
      model_dir: undefined,
      model_schema_hash: undefined,
      suggested_label: undefined,
      suggested_confidence: undefined,
      transition_count: 0,
      last_transition: undefined,
      labels_saved_count: 0,
      data_dir: "~/.taskclf",
      ui_port: 0,
      dev_mode: false,
      paused: false,
    }),
    active_suggestion: () => undefined,
    pending_suggestions: () => [],
    latest_prompt: () => undefined,
    live_status: () => undefined,
    label_grid_requested: () => 0,
    label_change_count: () => 0,
    connection_status: () => "connected" as const,
    ws_stats: () => ({
      message_count: 0,
      status_count: 0,
      prediction_count: 0,
      tray_state_count: 0,
      suggestion_count: 0,
      last_message_at: undefined,
      reconnect_count: 0,
      connected_since: undefined,
    }),
    train_state: () => ({
      job_id: undefined,
      status: "idle" as const,
      step: undefined,
      progress_pct: undefined,
      message: undefined,
      error: undefined,
      metrics: undefined,
      model_dir: undefined,
    }),
    suggestion_dismiss: vi.fn(),
    suggestion_select: vi.fn(),
  };
}
