import { vi } from "vitest";

/** Minimal `ws_store_new()` return for shell component tests. */
export function ws_store_stub() {
  return {
    latest_status: () => ({
      type: "status" as const,
      state: "idle" as const,
      current_app: "unknown",
      current_app_since: null,
      candidate_app: null,
      candidate_duration_s: 0,
      transition_threshold_s: 0,
      poll_seconds: 0,
      poll_count: 0,
      last_poll_ts: new Date(0).toISOString(),
      uptime_s: 0,
      aw_connected: false,
      aw_bucket_id: null,
      aw_host: "http://localhost:5600",
      last_event_count: 0,
      last_app_counts: {},
    }),
    latest_prediction: () => null,
    latest_tray_state: () => ({
      type: "tray_state" as const,
      model_loaded: false,
      model_dir: null,
      model_schema_hash: null,
      suggested_label: null,
      suggested_confidence: null,
      transition_count: 0,
      last_transition: null,
      labels_saved_count: 0,
      data_dir: "~/.taskclf",
      ui_port: 0,
      dev_mode: false,
      paused: false,
    }),
    active_suggestion: () => null,
    latest_prompt: () => null,
    live_status: () => null,
    label_grid_requested: () => 0,
    label_change_count: () => 0,
    connection_status: () => "connected" as const,
    ws_stats: () => ({
      message_count: 0,
      status_count: 0,
      prediction_count: 0,
      tray_state_count: 0,
      suggestion_count: 0,
      last_message_at: null,
      reconnect_count: 0,
      connected_since: null,
    }),
    train_state: () => ({
      job_id: null,
      status: "idle" as const,
      step: null,
      progress_pct: null,
      message: null,
      error: null,
      metrics: null,
      model_dir: null,
    }),
    suggestion_dismiss: vi.fn(),
  };
}
